spring:
  application:
    name: study-task-manager

  datasource:

    url: jdbc:sqlserver://localhost:1433;databaseName=study_task_manager;
      encrypt=true;trustServerCertificate=true
    username: sa
    password: sapassword
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.SQLServerDialect
        open-in-view: false

server:
  port: 8080
